name: CI-CD

on:
	push:
		branches: [ master ]
	workflow_dispatch:

jobs:
	build:
		name: Build and Publish
		runs-on: windows-latest

		steps:
			- name: Checkout
				uses: actions/checkout@v4

			- name: Setup .NET
				uses: actions/setup-dotnet@v4
				with:
					dotnet-version: '10.0.x'

			- name: Restore
				run: dotnet restore

			- name: Build
				run: dotnet build --configuration Release --no-restore

			- name: Test
				run: dotnet test --configuration Release --no-build --verbosity normal

			- name: Publish
				run: dotnet publish -c Release -o ./artifacts --no-build

			- name: Upload build artifacts
				uses: actions/upload-artifact@v4
				with:
					name: monitor-demo-artifacts
					path: artifacts

